# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'background_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from dataclasses import dataclass

@dataclass
class Geometry():
    x: int
    y: int
    size_x: int
    size_y: int

class Label():
    def __init__(self, parent: QWidget, geometry: Geometry, object_name: str, text: str):
        self = QtWidgets.QLabel(parent)
        self.setGeometry(QtCore.QRect(geometry.x, geometry.y, geometry.size_x, geometry.size_y))
        self.setObjectName(object_name)
        self.setText(text)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(304, 123)

        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setToolTipDuration(9)
        self.central_widget.setObjectName("central_widget")

        self.grid_widget = QtWidgets.QWidget(self.central_widget)
        self.grid_widget.setGeometry(QtCore.QRect(10, 10, 281, 101))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grid_widget.sizePolicy().hasHeightForWidth())
        self.grid_widget.setSizePolicy(sizePolicy)
        self.grid_widget.setObjectName("grid_widget")

        self.label_bird = Label(self.grid_widget, Geometry(10, 10, 100, 20), "Bird", 'Bird')
        self.label_city = Label(self.grid_widget, Geometry(10, 40, 100, 20), "City", 'City')
        self.label_bird = Label(self.grid_widget, Geometry(10, 70, 100, 20), "Rain", 'Rain')

        # self.label = QtWidgets.QLabel(self.grid_widget)
        # self.label.setGeometry(QtCore.QRect(10, 40, 100, 20))
        # self.label.setObjectName("label")
        # self.label_3 = QtWidgets.QLabel(self.grid_widget)
        # self.label_3.setGeometry(QtCore.QRect(10, 70, 100, 20))
        # self.label_3.setObjectName("label_3")


        self.pushButton = QtWidgets.QPushButton(self.grid_widget)
        self.pushButton.setGeometry(QtCore.QRect(120, 10, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setToolTipDuration(-1)
        self.pushButton.setStyleSheet("border: none")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Users/bo098/Pictures/play_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.grid_widget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 10, 20, 20))
        self.pushButton_4.setStyleSheet("border: none")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Users/bo098/Pictures/stop_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalSlider = QtWidgets.QSlider(self.grid_widget)
        self.horizontalSlider.setGeometry(QtCore.QRect(180, 10, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.grid_widget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(180, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_2.setSizePolicy(sizePolicy)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.grid_widget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 40, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setToolTipDuration(-1)
        self.pushButton_2.setStyleSheet("border: none")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.grid_widget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 70, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_3.setToolTipDuration(-1)
        self.pushButton_3.setStyleSheet("border: none")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.grid_widget)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 40, 20, 20))
        self.pushButton_5.setStyleSheet("border: none")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.grid_widget)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 70, 20, 20))
        self.pushButton_6.setStyleSheet("border: none")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.grid_widget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(180, 40, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_3.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_3.setSizePolicy(sizePolicy)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.label_2.setText(_translate("MainWindow", "TextLabel"))
        # self.label.setText(_translate("MainWindow", "TextLabel"))
        # self.label_3.setText(_translate("MainWindow", "TextLabel"))
